// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzrlegbchvhyjanibtkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6cmxlZ2JjaHZoeWphbmlidGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNDk2NzYsImV4cCI6MjA4NjYyNTY3Nn0.eJItD0TOmZrCguZkPCH7SoES_f2fHPzh08GvD6z3DmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});